

--
-- Volcado de datos para la tabla `registros_modbus`
--

INSERT INTO `registros_modbus` (`ID`, `direccion_modbus`, `registro`, `descripcion`, `rw`, `acceso`, `valor`) VALUES

(78, 78, 'HR_OUTPUT1_STATE', 'Estado actual de la salida K1/R1.', 'R', 'bit / 16 bits', NULL),
(79, 79, 'HR_OUTPUT2_STATE', 'Estado actual de la salida K2/R2.', 'R', 'bit / 16 bits', NULL),
(80, 80, 'HR_OUTPUT3_STATE', 'Estado actual de la salida K3/R3.', 'R', 'bit / 16 bits', NULL),
(81, 81, 'HR_OUTPUT4_STATE', 'Estado actual de la salida K4/R4.', 'R', 'bit / 16 bits', NULL),
(82, 82, 'HR_OUTPUT5_STATE', 'Estado actual de la salida K5.', 'R', 'bit / 16 bits', NULL),
(83, 83, 'HR_OUTPUT6_STATE', 'Estado actual de la salida K6.', 'R', 'bit / 16 bits', NULL),
(84, 84, 'HR_OUTPUT7_STATE', 'Estado actual de la salida K7.', 'R', 'bit / 16 bits', NULL),
(85, 85, 'HR_OUTPUT8_STATE', 'Estado actual de la salida K8.', 'R', 'bit / 16 bits', NULL),
(86, 94, 'HR_INTERNAL_TEMP', 'Valor de temperatura de la Junta Fría', 'R', '16 bits', NULL),
(87, 98, 'HR_STATUS_AI_CH1', 'LED de estado del canal A1.', 'R', '16 bits', NULL),
(88, 99, 'HR_STATUS_AI_CH2', 'LED de estado del canal A2.', 'R', '16 bits', NULL),
(89, 132, 'HR_INFO_ETH_IPV4_LO', 'Dirección IPv4.', 'R', '16 bits', NULL),
(90, 133, 'HR_INFO_ETH_IPv4_HI', 'Dirección IPv4.', 'R', '16 bits', NULL),
(91, 134, 'HR_INFO_ETH_IPV4_SBNT_MSK_LO', 'Máscara de subred IPv4 .', 'R', '16 bits', NULL),
(92, 135, 'HR_INFO_ETH_IPV4_SBNT_MSK_HI', 'Máscara de subred IPv4', 'R', '16 bits', NULL),
(93, 136, 'HR_INFO_ETH_IPV4_DFLT_GTWY_LO', 'Gateway IPv4 (Mismo formato de la dirección IP).', 'R', '16 bits', NULL),
(94, 137, 'HR_INFO_ETH_IPV4_DFLT_GTWY_HI', 'Gateway IPv4', 'R', '16 bits', NULL),
(95, 140, 'HR_TOTAL_SOCKETS', 'Número de sockets disponibles.', 'R', '16 bits', NULL),
(96, 141, 'HR_SOCKETS_IN_USE', 'Número de sockets en utilización.', 'R', '16 bits', NULL),
(97, 142, 'HR_GENERAL_ERROR_LO', 'Contador de errores de la interfaz Ethernet.', 'R', '16 bits', NULL),
(98, 143, 'HR_GENERAL_ERROR_HI', 'Contador de errores de la interfaz Ethernet.', 'R', '16 bits', NULL),
(99, 144, 'HR_RELISTEN_ERROR_LO', 'Contador de errores de relisten.', 'R', '16 bits', NULL),
(100, 145, 'HR_RELISTEN_ERROR_HI', 'Contador de errores de relisten.', 'R', '16 bits', NULL),
(101, 146, 'HR_SOCKET_SWITCH_ERROR_LO', 'Contador de errores de conmutación de los sockets.', 'R', '16 bits', NULL),
(102, 147, 'HR_SOCKET_SWITCH_ERROR_HI', 'Contador de errores de conmutación de los sockets.', 'R', '16 bits', NULL),
(103, 148, 'HR_DISCONNECT_ERROR_LO', 'Contador de errores de desconexión.', 'R', '16 bits', NULL),
(104, 149, 'HR_DISCONNECT_ERROR_HI', 'Contador de errores de desconexión.', 'R', '16 bits', NULL),
(105, 150, 'HR_SOCKET_CREATION_ERROR_LO', 'Contador de errores de creación de sockets.', 'R', '16 bits', NULL),
(106, 151, 'HR_SOCKET_CREATION_ERROR_HI', 'Contador de errores de creación de sockets.', 'R', '16 bits', NULL),
(107, 152, 'HR_SOCKET_DELETE_ERROR_LO', 'Contador de errores de sockets borrados.', 'R', '16 bits', NULL),
(108, 153, 'HR_SOCKET_DELETE_ERROR_HI', 'Contador de errores de sockets borrados.', 'R', '16 bits', NULL),
(109, 154, 'HR_IP_INVALID_PACKETS_LO', 'Número de paquetes no válidos recibidos.', 'R', '16 bits', NULL),
(110, 155, 'HR_IP_INVALID_PACKETS_HI', 'Número de paquetes no válidos recibidos.', 'R', '16 bits', NULL),
(111, 156, 'HR_PACKETS_SENT_LO', 'Número de paquetes enviados.', 'R', '16 bits', NULL),
(112, 157, 'HR_PACKETS_SENT_HI', 'Número de paquetes enviados.', 'R', '16 bits', NULL),
(113, 158, 'HR_PACKETS_RECEIVED_LO', 'Número de paquetes recibidos.', 'R', '16 bits', NULL),
(114, 159, 'HR_PACKETS_RECEIVED_HI', 'Número de paquetes recibidos.', 'R', '16 bits', NULL),
(115, 160, 'HR_ALLINPUTS_STATE', 'Concatena el estado de todas las entradas digitales', 'R', '16 bits', NULL),
(116, 162, 'HR_ALLOUTPUTS_STATE', 'Concatena el estado de todas las salidas digitales y relé', 'R', '16 bits', NULL),
(117, 500, 'HR_DO1_VALUE', 'Registro de manipulación del estado de la salida K1/R1.', 'R/W', '16 bits', NULL),
(118, 501, 'HR_DO2_VALUE', 'Registro de manipulación del estado de la salida K2/R2.', 'R/W', '16 bits', NULL),
(119, 502, 'HR_DO3_VALUE', 'Registro de manipulación del estado de la salida K3/R3.', 'R/W', '16 bits', NULL),
(120, 503, 'HR_DO4_VALUE', 'Registro de manipulación del estado de la salida K4/R4.', 'R/W', '16 bits', NULL),
(121, 504, 'HR_DO5_VALUE', 'Registro de manipulación del estado de la salida K5.', 'R/W', '16 bits', NULL),
(122, 505, 'HR_DO6_VALUE', 'Registro de manipulación del estado de la salida K6.', 'R/W', '16 bits', NULL),
(123, 506, 'HR_DO7_VALUE', 'Registro de manipulación del estado de la salida K7.', 'R/W', '16 bits', NULL),
(124, 507, 'HR_DO8_VALUE', 'Registro de manipulación del estado de la salida K8.', 'R/W', '16 bits', NULL);
