
--
-- Volcado de datos para la tabla `registros_modbus`
--

INSERT INTO `registros_modbus` (`ID`, `direccion_modbus`, `registro`, `descripcion`, `rw`, `acceso`, `valor`) VALUES
(1, 0, 'HR_NUM_SERIE_LO', 'Número de serie del dispositivo (1/2 registros)', 'R', '16 bits', NULL),
(2, 1, 'HR_NUM_SERIE_HI', 'Número de serie del dispositivo (2/2 registros)', 'R', '16 bits', NULL),
(3, 2, 'HR_HW_SET_LO', 'Configuración del hardware presente. (1/2 registros)', 'R', '16 bits', NULL),
(4, 3, 'HR_HW_SET_HI', 'Configuración del hardware presente. (2/2 registros)', 'R', '16 bits', NULL),
(5, 4, 'HR_ETH_MAC0', 'Dirección MAC de la interfaz Ethernet: 6H:6L:5H:5L:4H:4L', 'R', '16 bits', NULL),
(6, 5, 'HR_ETH_MAC1', 'Dirección MAC de la interfaz Ethernet: 6H:6L:5H:5L:4H:4L', 'R', '16 bits', NULL),
(7, 6, 'HR_ETH_MAC2', 'Dirección MAC de la interfaz Ethernet: 6H:6L:5H:5L:4H:4L', 'R', '16 bits', NULL),
(8, 7, 'HR_TS_CALIB0', 'Fecha de la última calibración (Unix Timestamp- UTC).', 'R', '16 bits', NULL),
(9, 8, 'HR_TS_CALIB1', 'Fecha de la última calibración (Unix Timestamp- UTC).', 'R', '16 bits', NULL),
(10, 9, 'HR_TS_CALIB2', 'Fecha de la última calibración (Unix Timestamp- UTC).', 'R', '16 bits', NULL),
(11, 10, 'HR_TS_CALIB3', 'Fecha de la última calibración (Unix Timestamp- UTC).', 'R', '16 bits', NULL),
(12, 11, 'HR_VERSAO_FW', 'Versión de firmware.', 'R', '16 bits', NULL),
(13, 12, 'HR_ID', 'Código de identificación: 0x0300 (hexadecimal).', 'R', '16 bits', NULL),
(14, 14, 'HR_AI1_LO', 'Valor leído de la entrada A1.', 'R', '16 bits', NULL),
(15, 15, 'HR_AI1_HI', 'Valor leído de la entrada A1.', 'R', '16 bits', NULL),
(16, 16, 'HR_AI2_LO', 'Valor leído de la entrada A2.', 'R', '16 bits', NULL),
(17, 17, 'HR_AI2_HI', 'Valor leído de la entrada A2.', 'R', '16 bits', NULL),
(18, 18, 'HR_AO1_LO', 'Valor actual de la salida O1.', 'R', '16 bits', NULL),
(19, 19, 'HR_AO1_HI', 'Valor actual de la salida O1.', 'R', '16 bits', NULL),
(20, 20, 'HR_AO2_LO', 'Valor actual de la salida O2.', 'R', '16 bits', NULL),
(21, 21, 'HR_AO2_HI', 'Valor actual de la salida O2.', 'R', '16 bits', NULL),
(22, 22, 'HR_COUNTER1_LO', 'Valor actual del contador de la entrada D1.', 'R', '16 bits', '14563'),
(23, 23, 'HR_COUNTER1_HI', 'Valor actual del contador de la entrada D1.', 'R', '16 bits', '0'),
(24, 24, 'HR_COUNTER2_LO', 'Valor actual del contador de la entrada D2.', 'R', '16 bits', '14494'),
(25, 25, 'HR_COUNTER2_HI', 'Valor actual del contador de la entrada D2.', 'R', '16 bits', '0'),
(26, 26, 'HR_COUNTER3_LO', 'Valor actual del contador de la entrada D3.', 'R', '16 bits', '0'),
(27, 27, 'HR_COUNTER3_HI', 'Valor actual del contador de la entrada D3.', 'R', '16 bits', '0'),
(28, 28, 'HR_COUNTER4_LO', 'Valor actual del contador de la entrada D4.', 'R', '16 bits', '0'),
(29, 29, 'HR_COUNTER4_HI', 'Valor actual del contador de la entrada D4.', 'R', '16 bits', '0'),
(30, 30, 'HR_COUNTER5_LO', 'Valor actual del contador de la entrada D5.', 'R', '16 bits', NULL),
(31, 31, 'HR_COUNTER5_HI', 'Valor actual del contador de la entrada D5.', 'R', '16 bits', NULL),
(32, 32, 'HR_COUNTER6_LO', 'Valor actual del contador de la entrada D6.', 'R', '16 bits', NULL),
(33, 33, 'HR_COUNTER6_HI', 'Valor actual del contador de la entrada D6.', 'R', '16 bits', NULL),
(34, 34, 'HR_COUNTER7_LO', 'Valor actual del contador de la entrada D7.', 'R', '16 bits', NULL),
(35, 35, 'HR_COUNTER7_HI', 'Valor actual del contador de la entrada D7.', 'R', '16 bits', NULL),
(36, 36, 'HR_COUNTER8_LO', 'Valor actual del contador de la entrada D8.', 'R', '16 bits', NULL),
(37, 37, 'HR_COUNTER8_HI', 'Valor actual del contador de la entrada D8.', 'R', '16 bits', NULL),
(38, 38, 'HR_DI1_TIME_ON_LO', 'Valor actual del integrador de tiempo \"ON\" de la entrada D1.', 'R', '16 bits', NULL),
(39, 39, 'HR_DI1_TIME_ON_HI', 'Valor actual del integrador de tiempo \"ON\" de la entrada D1.', 'R', '16 bits', NULL),
(40, 40, 'HR_DI2_TIME_ON_LO', 'Valor actual del integrador de tiempo \"ON\" de la entrada D2.', 'R', '16 bits', NULL),
(41, 41, 'HR_DI2_TIME_ON_HI', 'Valor actual del integrador de tiempo \"ON\" de la entrada D2.', 'R', '16 bits', NULL),
(42, 42, 'HR_DI3_TIME_ON_LO', 'Valor actual del integrador de tiempo \"ON\" de la entrada D3.', 'R', '16 bits', NULL),
(43, 43, 'HR_DI3_TIME_ON_HI', 'Valor actual del integrador de tiempo \"ON\" de la entrada D3.', 'R', '16 bits', NULL),
(44, 44, 'HR_DI4_TIME_ON_LO', 'Valor actual del integrador de tiempo \"ON\" de la entrada D4.', 'R', '16 bits', NULL),
(45, 45, 'HR_DI4_TIME_ON_HI', 'Valor actual del integrador de tiempo \"ON\" de la entrada D4.', 'R', '16 bits', NULL),
(46, 46, 'HR_DI5_TIME_ON_LO', 'Valor actual del integrador de tiempo \"ON\" de la entrada D5.', 'R', '16 bits', NULL),
(47, 47, 'HR_DI5_TIME_ON_HI', 'Valor actual del integrador de tiempo \"ON\" de la entrada D5.', 'R', '16 bits', NULL),
(48, 48, 'HR_DI6_TIME_ON_LO', 'Valor actual del integrador de tiempo \"ON\" de la entrada D6.', 'R', '16 bits', NULL),
(49, 49, 'HR_DI6_TIME_ON_HI', 'Valor actual del integrador de tiempo \"ON\" de la entrada D6.', 'R', '16 bits', NULL),
(50, 50, 'HR_DI7_TIME_ON_LO', 'Valor actual del integrador de tiempo \"ON\" de la entrada D7.', 'R', '16 bits', NULL),
(51, 51, 'HR_DI7_TIME_ON_HI', 'Valor actual del integrador de tiempo \"ON\" de la entrada D7.', 'R', '16 bits', NULL),
(52, 52, 'HR_DI8_TIME_ON_LO', 'Valor actual del integrador de tiempo \"ON\" de la entrada D8.', 'R', '16 bits', NULL),
(53, 53, 'HR_DI8_TIME_ON_HI', 'Valor actual del integrador de tiempo \"ON\" de la entrada D8.', 'R', '16 bits', NULL),
(54, 54, 'HR_DI1_TIME_OFF_LO', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D1.', 'R', '16 bits', NULL),
(55, 55, 'HR_DI1_TIME_OFF_HI', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D1.', 'R', '16 bits', NULL),
(56, 56, 'HR_DI2_TIME_OFF_LO', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D2.', 'R', '16 bits', NULL),
(57, 57, 'HR_DI2_TIME_OFF_HI', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D2.', 'R', '16 bits', NULL),
(58, 58, 'HR_DI3_TIME_OFF_LO', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D3.', 'R', '16 bits', NULL),
(59, 59, 'HR_DI3_TIME_OFF_HI', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D3.', 'R', '16 bits', NULL),
(60, 60, 'HR_DI4_TIME_OFF_LO', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D4.', 'R', '16 bits', NULL),
(61, 61, 'HR_DI4_TIME_OFF_HI', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D4.', 'R', '16 bits', NULL),
(62, 62, 'HR_DI5_TIME_OFF_LO', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D5.', 'R', '16 bits', NULL),
(63, 63, 'HR_DI5_TIME_OFF_HI', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D5.', 'R', '16 bits', NULL),
(64, 64, 'HR_DI6_TIME_OFF_LO', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D6.', 'R', '16 bits', NULL),
(65, 65, 'HR_DI6_TIME_OFF_HI', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D6.', 'R', '16 bits', NULL),
(66, 66, 'HR_DI7_TIME_OFF_LO', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D7.', 'R', '16 bits', NULL),
(67, 67, 'HR_DI7_TIME_OFF_HI', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D7.', 'R', '16 bits', NULL),
(68, 68, 'HR_DI8_TIME_OFF_LO', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D8.', 'R', '16 bits', NULL),
(69, 69, 'HR_DI8_TIME_OFF_HI', 'Valor actual del integrador de tiempo \"OFF\" de la entrada D8.', 'R', '16 bits', NULL),
(70, 70, 'HR_INPUT1_STATE', 'Estado de la entrada D1.', 'R', 'bit / 16 bits', '0'),
(71, 71, 'HR_INPUT2_STATE', 'Estado de la entrada D2.', 'R', 'bit / 16 bits', '0'),
(72, 72, 'HR_INPUT3_STATE', 'Estado de la entrada D3.', 'R', 'bit / 16 bits', '0'),
(73, 73, 'HR_INPUT4_STATE', 'Estado de la entrada D4.', 'R', 'bit / 16 bits', '0'),
(74, 74, 'HR_INPUT5_STATE', 'Estado de la entrada D5.', 'R', 'bit / 16 bits', NULL),
(75, 75, 'HR_INPUT6_STATE', 'Estado de la entrada D6.', 'R', 'bit / 16 bits', NULL),
(76, 76, 'HR_INPUT7_STATE', 'Estado de la entrada D7.', 'R', 'bit / 16 bits', NULL),
(77, 77, 'HR_INPUT8_STATE', 'Estado de la entrada D8.', 'R', 'bit / 16 bits', NULL);